import { getProjectById } from "@/actions/getProjectById";
import ProjectLayout from "@/components/project/ProjectLayout";
import ProjectOverview from "@/components/project/containers/ProjectOverview";
import { notFound } from "next/navigation";
import { FC } from "react";

interface ProjectPageProps {
  params: {
    projectId: string;
  };
}

export const metadata = {
  title: "Project Overview | Tasky",
  description: "Generated by create next app",
};

const page: FC<ProjectPageProps> = async ({ params }) => {
  const { projectId } = params;
  const project = await getProjectById(projectId);

  if (!project) {
    notFound();
  }

  return (
    <ProjectLayout project={project} activeTab="overview">
      <ProjectOverview project={project} tasks={project.tasks} />
    </ProjectLayout>
  );
};

export default page;
