import React from "react";

export const metadata = {
  title: "features | tasky",
  description: "Generated by create next app",
};
export default function features() {
  return <div>features</div>;
}
