import { getProjects } from "@/actions/getProjects";
import AddEntityModal from "@/components/AddEntityModal";
import AddProjectForm from "@/components/project/AddProjectForm";
import PageHeader from "@/components/PageHeader";
import ProjectsSection from "@/components/project/ProjectsSection";
import {
  EmptyState,
  EmptyStateActions,
  EmptyStateContent,
  EmptyStateDescription,
  EmptyStateIcon,
  EmptyStateTitle,
} from "@/components/ui/empty-state";
import { Folder } from "lucide-react";
import React from "react";

export const metadata = {
  title: "Projects | Tasky",
  description: "Generated by create next app",
};

export default async function projects() {
  const projects = await getProjects();
  return (
    <div className="flex flex-col gap-y-6 md:gap-y-8">
      <PageHeader
        title="projects"
        description="Here's a list of your projects!"
      >
        <AddEntityModal
          entity="project"
          form={<AddProjectForm />}
          ButtonVariant="default"
        />
      </PageHeader>
      {!projects.length ? (
        <EmptyState className="mt-4 md:mt-6 lg:mt-8">
          <EmptyStateContent>
            <EmptyStateIcon>
              <Folder className="w-10 h-10" />
            </EmptyStateIcon>
            <EmptyStateTitle>No projects added</EmptyStateTitle>
            <EmptyStateDescription>
              You have not added any projects. Add one below.
            </EmptyStateDescription>
            <EmptyStateActions>
              <AddEntityModal
                entity="project"
                form={<AddProjectForm />}
                ButtonVariant="default"
              />
            </EmptyStateActions>
          </EmptyStateContent>
        </EmptyState>
      ) : (
        <ProjectsSection projects={projects} />
      )}
    </div>
  );
}
