import { getProjectById } from "@/actions/getProjectById";
import ProjectLayout from "@/components/project/ProjectLayout";
import ProjectSettings from "@/components/project/containers/ProjectSettings";
import { notFound } from "next/navigation";
import { FC } from "react";

interface pageProps {
  params: {
    projectId: string;
  };
}

export const metadata = {
  title: "Project Settings | Tasky",
  description: "Generated by create next app",
};

const page: FC<pageProps> = async ({ params }) => {
  const { projectId } = params;
  const project = await getProjectById(projectId);

  if (!project) {
    notFound();
  }
  return (
    <ProjectLayout project={project} activeTab="settings">
      <ProjectSettings project={project} />
    </ProjectLayout>
  );
};

export default page;
