import { FC } from "react";
import PageHeader from "@/components/PageHeader";
import { getTeamById } from "@/actions/getTeamById";
import { notFound } from "next/navigation";
import TeamLayout from "@/components/teams/TeamLayout";
import StatisticCard from "@/components/StatisticCard";
import { getMembers } from "@/actions/getMembers";
import { User } from "lucide-react";

interface TeamPageProps {
  params: {
    teamId: string;
  };
}

export const metadata = {
  title: "Team Overview | Tasky",
  description: "Generated by create next app",
};

const page: FC<TeamPageProps> = async ({ params }) => {
  const team = await getTeamById(params.teamId);
  const members = await getMembers(team?.id);

  if (!team) {
    notFound();
  }

  return (
    <TeamLayout Team={team} activeTab="overview">
      <section className="flex flex-col gap-6 md:gap-8 mt-8">
        <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <StatisticCard
            title="total members"
            value={members?.length!}
            icon={<User />}
            percentageChange={5}
            description="test"
            unit="tasks"
          />
          {/* <StatisticCard
          title="completed tasks"
          value={completedTasks.length}
          icon={<ClipboardCheck />}
          percentageChange={5}
          description="test"
          unit="tasks"
        /> */}
          {/* <StatisticCard
          title="project progress"
          value={projectProgress}
          icon={<TrendingUp />}
          percentageChange={5}
          description="test"
          unit="%"
        /> */}
        </section>
        <section className="grid grid-cols-12 gap-4">
          <p className="col-span-12 lg:col-span-8">hi!</p>
          {/* <ProjectTasksClassment data={data} tasksCount={tasks?.length!} /> */}
        </section>
      </section>
    </TeamLayout>
  );
};

export default page;
