import { getCompletedTasks } from "@/actions/getCompletedTasks";
import { getProjects } from "@/actions/getProjects";
import PageHeader from "@/components/PageHeader";
import StatisticCard from "@/components/StatisticCard";
import { Card, CardDescription, CardTitle } from "@/components/ui/card";
import { Check, Folders } from "lucide-react";

export const metadata = {
  title: "welcome to your dashboard | tasky",
  description: "Generated by create next app",
};
export default async function dashboard() {
  const projects = await getProjects();
  const completedTasks = await getCompletedTasks();
  return (
    <div className="flex flex-col gap-y-6 md:gap-y-8">
      <PageHeader title="dashboard" />
      {/* staistics cards */}
      <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatisticCard
          title="Total projects"
          icon={<Folders />}
          value={projects.length}
          percentageChange={100}
          description="test desc"
          unit="projects"
        />
        <StatisticCard
          title="Completed Tasks"
          icon={<Check />}
          value={completedTasks.length}
          percentageChange={100}
          description="test desc"
          unit="tasks"
        />
      </section>
      {/* staistics cards */}

      <section className="grid grid-cols-12 gap-4">
        <Card className="col-span-12 lg:col-span-7">
          <CardTitle>Recent news</CardTitle>
          <CardDescription>
            Your teams complete 43 tasks this week
          </CardDescription>
        </Card>
        <Card className="col-span-12 lg:col-span-5">
          <CardTitle>Recent news</CardTitle>
          <CardDescription>
            Your teams complete 43 tasks this week
          </CardDescription>
        </Card>
      </section>
    </div>
  );
}
