import { getTeams } from "@/actions/getTeams";
import AddEntityModal from "@/components/AddEntityModal";
import PageHeader from "@/components/PageHeader";
import AddTeamForm from "@/components/teams/AddTeamForm";
import TeamsSection from "@/components/teams/TeamsSection";
import {
  EmptyState,
  EmptyStateActions,
  EmptyStateContent,
  EmptyStateDescription,
  EmptyStateIcon,
  EmptyStateTitle,
} from "@/components/ui/empty-state";
import { Users } from "lucide-react";
import React from "react";

export const metadata = {
  title: "Teams | Tasky",
  description: "Generated by create next app",
};

export default async function teams() {
  const teams = await getTeams();
  return (
    <div className="flex flex-col gap-y-6 md:gap-y-8">
      <PageHeader title="Teams" description="Here's a list of your teams!">
        <AddEntityModal
          entity="team"
          form={<AddTeamForm />}
          ButtonVariant="default"
        />
      </PageHeader>
      {!teams?.length ? (
        <EmptyState className="mt-4 md:mt-6 lg:mt-8">
          <EmptyStateContent>
            <EmptyStateIcon>
              <Users className="w-10 h-10" />
            </EmptyStateIcon>
            <EmptyStateTitle>No teams added</EmptyStateTitle>
            <EmptyStateDescription>
              You have not added any teams. Add one below.
            </EmptyStateDescription>
            <EmptyStateActions>
              <AddEntityModal
                entity="team"
                form={<AddTeamForm />}
                ButtonVariant="default"
              />
            </EmptyStateActions>
          </EmptyStateContent>
        </EmptyState>
      ) : (
        <TeamsSection teams={teams!} />
      )}
    </div>
  );
}
