import { getProjectById } from "@/actions/getProjectById";
import ProjectLayout from "@/components/project/ProjectLayout";
import TasksTable from "@/components/project/containers/TasksTable";
import { TabsContent } from "@/components/ui/tabs";
import { notFound } from "next/navigation";
import React, { FC } from "react";

interface ProjectPageProps {
  params: {
    projectId: string;
  };
}

export const metadata = {
  title: "Tasks | Tasky",
  description: "Generated by create next app",
};

const page: FC<ProjectPageProps> = async ({ params }) => {
  const { projectId } = params;
  const project = await getProjectById(projectId);

  if (!project) {
    notFound();
  }
  return (
    <ProjectLayout project={project} activeTab="tasks">
      <TasksTable projectId={project.id} />
    </ProjectLayout>
  );
};

export default page;
